#!/bin/bash
export BOT_TOKEN=MzUyMjkxMjkwNTg0NTgwMDk2.XSzCJA.wtH-N7mzghGVhD8by37B_D8xiOo
#echo $BOT_TOKEN
adddate(){
	while IFS= read -r line; do
		printf '%s %s \n' "$(date '+%D %H:%M')" "$line";
	done
}

#date '+%D %H:%M' >> /home/vidovi/discord/log.txt
#stdbuf -oL python3 /home/vidovi/discord/main.py >> /home/vidovi/discord/log.txt

python3 -u /home/vidovi/discord/main.py | adddate &>> /home/vidovi/discord/log.txt

